Opcode01/Slideshow-Creator

- README.md
Empowers users to select and arrange photos into a slideshow
> Renamed repo, added short description

- Slideshow-Creator/src/core/SceneHandler.java
- Slideshow-Creator/src/creator/CreatorMain.java
- Slideshow-Creator/src/viewer/ViewerMain.java
Set up the JFrame for the program, set up the main function for viewer and creator to load the program with different app type. Woot!
(0.5) Main Injection point (viewer) https://trello.com/c/caiplCC4
(0.5) Main Injection point (creator) https://trello.com/c/IoDjfvC1
> Created main frame, created main functions to load up different programs

- .gitignore
- Slideshow-Creator/src/core/Thumbnail.java
Added Thumbnail(imagePath) creates thumbnail with path and image
imageRaw holds the image straight from the file
imagePath and imageRaw are publicly gettable
> Thumbnail holds image path

- Slideshow-Creator/src/core/Scene.java
- Slideshow-Creator/src/core/SceneHandler.java
- Slideshow-Creator/src/core/SceneType.java
- Slideshow-Creator/src/core/Thumbnail.java
- Slideshow-Creator/src/creator/DirectoryExplorer.java
- Slideshow-Creator/src/creator/SelectScene.java
- Made SceneHandler a singleton
- Added tracked directory to SceneHandler
- Made SceneHandler appType private
- Made Scene an abstract class
- Fleshed out Scene to have init, show, and hide
- Created transition from DirectoryExplorer to SelectScene
- Removed weird panel that exists at the start of the program
- Removed hiding and showing frame when swapping scenes
- Moved getters and setters under respective variables
Boy, I did a lot *phew* aahhh I love programming. I'm such a nerd
> Transition from Directory Explorer to Select Scene

- Slideshow-Creator/src/core/SceneHandler.java
mainFrame.revalidate();
mainFrame.repaint();
Woot
> Fixed window not repainting on returning to existing scene

- Slideshow-Creator/src/core/Coord2.java
- Slideshow-Creator/src/core/Thumbnail.java
- Created Coord2 class in core that stores x and y
- Added resized thumbnail imageThumb
> Created Coord2 class, added thumbnail rescale

- Slideshow-Creator/src/core/FloatingPane.java
- Slideshow-Creator/src/core/SceneHandler.java
- Slideshow-Creator/src/creator/ArrangeScene.java
- Slideshow-Creator/src/creator/SelectScene.java
- Slideshow-Creator/src/creator/SettingsPane.java
- Slideshow-Creator/src/creator/TransitionPane.java
completed user story Pane Class
- also includes the commits from the scene-handler pull request because they were merged into this branch, don't worry about this though git should handle it fine
> Pane class

- Slideshow-Creator/src/core/SceneHandler.java
- Slideshow-Creator/src/creator/ArrangeScene.java
- Slideshow-Creator/src/creator/SelectScene.java
Completed User Stories:
- Get Scene Instance By Type
- Add tooltips to creator
> Scene handler

- Slideshow-Creator/src/core/SceneHandler.java
Added quit confirmation dialog. Run every time exit button is closed.
> Added quit confirmation dialog

- Slideshow-Creator/src/core/AudioPlayer.java
- Slideshow-Creator/src/creator/AudioTimeline.java
- Slideshow-Creator/src/viewer/AudioPlayer.java
Moved AudioPlayer to core and replaced AudioTimeline's functionality with AudioPlayer according to design discussions.
> Moved AudioPlayer to Core, removed AudioTimeline

- Slideshow-Creator/src/core/Coord2.java
- Slideshow-Creator/src/core/SceneHandler.java
- Slideshow-Creator/src/creator/ArrangeScene.java
- Made SceneHandler.mainFrame private, added getMainFrame()
- Made Coord2 immutable
- Renamed setNewTimeline to setTimeline
> Misc changes to align with Architectural Design Document

- Slideshow-Creator/src/core/SceneHandler.java
- Slideshow-Creator/src/core/TimelineParser.java
- Slideshow-Creator/src/creator/DirectoryExplorer.java
- Made file select work because I needed it for this task
- Initialized timeline based on directory and on file
> Added file select functionality, initialized timeline

- Slideshow-Creator/src/core/Timeline.java
- Slideshow-Creator/src/core/Transition.java
- Slideshow-Creator/src/core/TransitionType.java
- Slideshow-Creator/src/creator/SelectScene.java
- Slideshow-Creator/src/creator/TransitionPane.java
- Slideshow-Creator/src/pkgImageTransitions/ColemanTransition.java
- Slideshow-Creator/src/pkgImageTransitions/ImagePanel.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_CrossDissolve.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_PushDown.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_PushLeft.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_PushRight.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_PushUp.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_WipeDown.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_WipeLeft.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_WipeRight.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_WipeUp.java
Backend implementation for creating a new transition and modifying its type and duration
> Transitions core

- Slideshow-Creator/src/core/Timeline.java
- Slideshow-Creator/src/creator/ArrangeScene.java
- Slideshow-Creator/src/creator/SettingsPane.java
- Slideshow-Creator/src/creator/TransitionPane.java
Settings pane and transition pane now update based on their current settings. Arrange scene revalidates when transitions are changed
> Settings pane loading

- Slideshow-Creator/src/core/Audio.java
- Slideshow-Creator/src/core/AudioPlayer.java
- Slideshow-Creator/src/core/Timeline.java
- Slideshow-Creator/src/core/TimelineParser.java
This should be what you guys need for audio list exporting/importing things
> Audio list

- Slideshow-Creator/src/creator/ArrangeScene.java
- Slideshow-Creator/src/creator/DirectoryExplorer.java
- Slideshow-Creator/src/creator/WarningPane.java
I've modified the warning pane so that it can say any text we want without re-writing or needing to extend the class. We can later use this to handle and display exceptions
> Extensible Warning Pane

- Slideshow-Creator/src/core/Scene.java
- Slideshow-Creator/src/core/SceneHandler.java
- Slideshow-Creator/src/creator/SelectScene.java
- Removed prompt in viewer
- Made prompt when leaving Select Scene
- Removed prompt in directory explorer
I could make it a warning pane if we made Yes and No buttons, but it doesn't feel worth it at this point.
> Polish exit prompt

- Slideshow-Creator/src/core/ThumbnailsList.java
- Slideshow-Creator/src/core/TimelineParser.java
- Slideshow-Creator/src/core/TransitionsList.java
- Slideshow-Creator/src/creator/ArrangeScene.java
- Slideshow-Creator/src/creator/DirectoryExplorer.java
- Slideshow-Creator/src/creator/SelectScene.java
- Slideshow-Creator/src/viewer/FileSelectExplorer.java
- Slideshow-Creator/src/viewer/ViewerMain.java
This seems to be a more stable build. I'll have to pull in the transition fixes to really check these out though.
> Slider exceptions

- Slideshow-Creator/src/viewer/PlayScene.java
> Made controls bar black

- Slideshow-Creator/src/creator/ArrangeScene.java
- Slideshow-Creator/src/creator/SelectScene.java
change directory current locations
> Final fixes

- Slideshow-Creator/src/core/Audio.java
- Slideshow-Creator/src/core/TimelineParser.java
- Slideshow-Creator/src/core/WarningPane.java
- Slideshow-Creator/src/viewer/FileSelectExplorer.java
- Slideshow-Creator/src/viewer/ViewerMain.java
Austin made it show a warning and be sad when you try to pull in a lost audio file.
> Handled a lost audio file

- Slideshow-Creator/src/creator/TransitionPane.java
- Slideshow-Creator/src/viewer/PlayScene.java
> Tooltip fixes

- Slideshow-Creator/src/core/AudioPlayer.java
- Slideshow-Creator/src/core/SliderColor.java
- Slideshow-Creator/src/core/Transition.java
- Slideshow-Creator/src/creator/DirectoryExplorer.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_CrossDissolve.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_WipeDown.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_WipeLeft.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_WipeRight.java
- Slideshow-Creator/src/pkgImageTransitions/Transitions/Trans_WipeUp.java
- Slideshow-Creator/src/viewer/FileSelectExplorer.java
- Slideshow-Creator/src/viewer/PlayScene.java
- Slideshow-Creator/src/viewer/SlideShowTime.java
Fixed transitions, colors, good stuff
> Misc fixes
